'use client';

import Navbar from '@/components/layout/Navbar';
import SideNav from '@/components/layout/SideNav';
import localFont from 'next/font/local';
import { useState } from 'react';
import '../globals.css';
import { Providers } from '../providers';

const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="flex min-h-screen">
            {/* <Sidebar/> */}
            <SideNav
              isOpen={sidebarOpen}
              onClose={() => setSidebarOpen(false)}
            />
            <div className="flex flex-col flex-1">
              <Navbar onToggleSidebar={() => setSidebarOpen(true)} />
              <main className="flex-1 p-4 dark:bg-black light:bg-white overflow-y-auto">
                {children}
              </main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
